'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'

type RoomState = Record<string,string>

const levels=['Fisico','Collegamento dati','Rete','Trasporto','Sessione','Presentazione','Applicazione']
const cli=['enable','configure terminal','interface g0/0','ip address 192.168.10.1 255.255.255.0','no shutdown','ip route 192.168.20.0 255.255.255.0 10.0.0.2']

function Panel({title,children}: {title:string,children:React.ReactNode}){return <section className="challenge-panel"><div className="panel-head"><span>{title}</span><i/></div>{children}</section>}

export default function RoomChallenge({roomId}:{roomId:number}){
 const router=useRouter(); const [a,setA]=useState<RoomState>({}); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 const [step,setStep]=useState(1)
 const packet=[['A','PORTA DESTINAZIONE','443'],['B','MAC SORGENTE','AA:7B:19:CC:04:91'],['C','IP DESTINAZIONE','172.16.40.20'],['D','PROTOCOLLO','HTTPS']]
 const vlsm=[['SEGRETERIA','60'],['LAB','120'],['SERVER','28'],['GUEST','14']]
 const rooms=useMemo(()=>({1:'ENCAPSULATION',2:'VLSM',3:'CIDR',4:'NEXT-HOP',5:'DIAGNOSI',6:'VLAN',7:'REDUNDANZA',8:'SYNORA'} as Record<number,string>),[])
 function set(k:string,v:string){setA(x=>({...x,[k]:v}));setMsg('')}
 async function submit(){setBusy(true);setMsg('VERIFICA DELLA TRACCIA SUL CORE…'); const res=await fetch('/api/attempt',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({roomId,answers:a})}); const data=await res.json(); setBusy(false); setMsg(data.message); if(data.success){setStep(2); setTimeout(()=>router.push('/synora'),1200)}}
 const title=rooms[roomId]
 return <div className="challenge-wrap">
   <div className="challenge-progress"><span className="active">01 TRACCIA</span><span>02 VERIFICA</span><span>03 CHIAVE</span><div><b>{title}</b> · protocollo locale</div></div>
   {roomId===1 && <Panel title="TRACE / FRAME 0017"><p className="instruction">Quattro frammenti sono stati recuperati. Attribuiteli al livello corretto. Poi ricostruite la sequenza di incapsulamento.</p><div className="packet-grid">{packet.map(([id,k,v])=><div className="packet-chip" key={id}><b>{id}</b><span>{k}</span><code>{v}</code><select value={a[id]||''} onChange={e=>set(id,e.target.value)}><option value="">livello…</option>{levels.map(x=><option key={x}>{x}</option>)}</select></div>)}</div><div className="mini-question"><span>Ordine di rimozione degli header</span><select value={a.order||''} onChange={e=>set('order',e.target.value)}><option value="">scegli…</option><option>Applicazione → Trasporto → Rete → Collegamento</option><option>Collegamento → Rete → Trasporto → Applicazione</option><option>Trasporto → Applicazione → Rete → Collegamento</option></select></div></Panel>}
   {roomId===2 && <Panel title="ADDRESSING / VLSM"><p className="instruction">La rete 192.168.40.0/24 deve contenere quattro segmenti. Ordinate le richieste dalla più grande alla più piccola e assegnate il prefisso minimo corretto.</p><div className="vlsm-grid">{vlsm.map(([name,n],i)=><div className="vlsm-row" key={name}><b>{name}</b><span>{n} host</span><select value={a[`p${i}`]||''} onChange={e=>set(`p${i}`,e.target.value)}><option value="">/ ?</option>{['/25','/26','/27','/28','/29','/30'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="rete (es. 192.168.40.0)" value={a[`r${i}`]||''} onChange={e=>set(`r${i}`,e.target.value)}/></div>)}</div><div className="mini-question"><span>Primo indirizzo utilizzabile del segmento più grande</span><input value={a.first||''} onChange={e=>set('first',e.target.value)} placeholder="x.x.x.x"/></div></Panel>}
   {roomId===3 && <Panel title="AGGREGATION / CIDR"><p className="instruction">Quattro reti contigue devono essere annunciate con una sola rotta. Individuate il blocco aggregato e verificate che nessuna rete esterna venga inglobata.</p><div className="route-list">{['172.16.32.0/24','172.16.33.0/24','172.16.34.0/24','172.16.35.0/24'].map(x=><code key={x}>{x}</code>)}</div><div className="answer-pair"><label>Supernet</label><select value={a.cidr||''} onChange={e=>set('cidr',e.target.value)}><option value="">scegli…</option><option>172.16.32.0/22</option><option>172.16.32.0/23</option><option>172.16.30.0/22</option></select><label>Maschera decimale</label><input value={a.mask||''} onChange={e=>set('mask',e.target.value)} placeholder="255.255.x.0"/></div><div className="mini-question"><span>Quante /24 contiene il blocco?</span><input value={a.count||''} onChange={e=>set('count',e.target.value)} placeholder="numero"/></div></Panel>}
   {roomId===4 && <Panel title="ROUTING / TRACEROUTE"><p className="instruction">Un traceroute mostra tre hop. Il quarto non risponde. La tabella di routing del router locale contiene tre righe: scegliete il next-hop coerente con la destinazione 10.20.30.0/24.</p><div className="trace"><div><span>01</span><code>192.168.1.1</code><small>LOCAL GATEWAY</small></div><div><span>02</span><code>10.0.0.2</code><small>CORE</small></div><div><span>03</span><code>10.0.1.2</code><small>EDGE</small></div><div className="lost"><span>04</span><code>* * *</code><small>NO REPLY</small></div></div><div className="answer-pair"><label>Next-hop per 10.20.30.0/24</label><select value={a.next||''} onChange={e=>set('next',e.target.value)}><option value="">scegli…</option><option>10.0.0.2</option><option>10.0.1.2</option><option>192.168.1.1</option></select><label>Tipo di rotta di backup</label><select value={a.def||''} onChange={e=>set('def',e.target.value)}><option value="">scegli…</option><option>default route</option><option>connected</option><option>host route</option></select></div></Panel>}
   {roomId===5 && <Panel title="ROUTER / DIAGNOSTIC"><p className="instruction">Tre righe di configurazione sembrano plausibili. Una sola è incompatibile con la topologia. Individuate l’errore e correggetelo.</p><pre className="terminal">R5# show ip route{`\n`}C 10.0.5.0/30 is directly connected, GigabitEthernet0/1{`\n`}S 192.168.50.0/24 [1/0] via 10.0.5.2{`\n`}S 192.168.60.0/24 [1/0] via 10.0.6.2{`\n`}{`\n`}R5# show ip interface brief{`\n`}Gi0/0   192.168.5.1   up   up{`\n`}Gi0/1   10.0.5.1      up   up{`\n`}Gi0/2   10.0.6.1      administratively down</pre><div className="answer-pair"><label>Errore</label><select value={a.err||''} onChange={e=>set('err',e.target.value)}><option value="">scegli…</option><option>La rotta verso 192.168.50.0 è incoerente</option><option>La rotta verso 192.168.60.0 usa un'interfaccia down</option><option>Gi0/0 ha un IP errato</option></select><label>Azione</label><select value={a.fix||''} onChange={e=>set('fix',e.target.value)}><option value="">scegli…</option><option>no shutdown su Gi0/2</option><option>cancellare la rotta 192.168.60.0</option><option>cambiare IP a Gi0/0</option></select></div></Panel>}
   {roomId===6 && <Panel title="SEGMENTATION / VLAN"><p className="instruction">Uno switch trasporta tre reti: STAFF, LAB e GUEST. Le porte 1–8 sono accesso; la porta 24 è il collegamento verso il router. Ricostruite la separazione logica.</p><div className="switch-grid">{[1,2,3,4,5,6,7,8,24].map(p=><div key={p} className={`port ${p===24?'trunk':''}`}><span>Gi{p}</span><select value={a[`v${p}`]||''} onChange={e=>set(`v${p}`,e.target.value)}><option value="">VLAN</option><option>10 STAFF</option><option>20 LAB</option><option>30 GUEST</option><option>TRUNK</option></select></div>)}</div><div className="mini-question"><span>Quale dominio di broadcast deve attraversare il router?</span><select value={a.broadcast||''} onChange={e=>set('broadcast',e.target.value)}><option value="">scegli…</option><option>tutti e tre separatamente</option><option>una sola LAN comune</option><option>solo GUEST</option></select></div></Panel>}
   {roomId===7 && <Panel title="REDUNDANCY / STP"><p className="instruction">Tre switch formano un triangolo. La ridondanza è desiderata, il loop no. Analizzate i costi e scegliete il collegamento che STP dovrà bloccare.</p><div className="triangle"><div className="sw s1">SW1<small>BID 01</small></div><div className="sw s2">SW2<small>BID 02</small></div><div className="sw s3">SW3<small>BID 03</small></div><div className="edge e1"><span>10</span></div><div className="edge e2"><span>10</span></div><div className="edge e3"><span>100</span></div></div><div className="answer-pair"><label>Root Bridge</label><select value={a.root||''} onChange={e=>set('root',e.target.value)}><option value="">scegli…</option><option>SW1</option><option>SW2</option><option>SW3</option></select><label>Link da bloccare</label><select value={a.block||''} onChange={e=>set('block',e.target.value)}><option value="">scegli…</option><option>SW1 — SW2</option><option>SW2 — SW3</option><option>SW1 — SW3</option></select></div></Panel>}
   {roomId===8 && <Panel title="TERMINAL / CISCO CLI"><p className="instruction">Il core è tornato raggiungibile. Ora dovete ricostruire una piccola configurazione. Inserite i comandi nell’ordine corretto.</p><div className="cli-builder">{cli.map((x,i)=><div key={x} className="cli-row"><span>{i+1}</span><code>{x}</code><select value={a[`c${i}`]||''} onChange={e=>set(`c${i}`,e.target.value)}><option value="">posizione</option>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></div>)}</div><div className="mini-question"><span>Quale comando rende operativa l’interfaccia?</span><select value={a.up||''} onChange={e=>set('up',e.target.value)}><option value="">scegli…</option><option>no shutdown</option><option>enable</option><option>configure terminal</option></select></div></Panel>}
   <div className="challenge-actions"><div>{msg && <div className={`result ${msg.includes('CORRETTA')||msg.includes('COMPLETATO')?'ok':'bad'}`}>{msg}</div>}</div><button className="cta cta-small" disabled={busy} onClick={submit}>{busy?'VERIFICA…':'INVIA AL CORE  →'}</button></div>
   <div className="anti-ai"><span>◈</span><div><b>PROTOCOLLO DI VERIFICA</b><p>La risposta viene controllata sul server insieme alla coerenza della traccia. Non è sufficiente fornire una parola chiave: ogni passaggio deve essere compatibile con gli altri.</p></div></div>
 </div>
}
